apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dittnav-api
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{version}}
  port: 8090
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    path: /metrics
  replicas:
    min: 1
    max: 1
  webproxy: true
  ingresses:
    - "https://dittnav-api.nais.oera-q.local"
    - "https://dittnav-api.dev-sbs.nais.io"
    - "https://www-q1.nav.no/person/dittnav-api"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: true
