apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dittnav-api
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /person/dittnav-api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /person/dittnav-api/internal/isReady
    initialDelay: 10
  prometheus:
    path: /person/dittnav-api/metrics
  replicas:
    min: 2
    max: 4
  webproxy: true
  ingresses: {{ingresses}}
  vault:
    enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
