name: Trigg visning av deploy-knapper i slack

on:
  repository_dispatch:
    types: show-slack-buttons

env:
  COMMIT_BRANCH: ${{ github.event.client_payload.branch }}
  COMMIT_SHA: ${{ github.event.client_payload.commit }}
  ALLOW_PROD: ${{ github.event.client_payload.allow_prod }}

jobs:
  show-slack-buttons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Vis deploy-knapper i slack
        uses: navikt/deploy-trigger-slack-integration@v1
        with:
          slack_channel: "#dittnav-deploy-actions"
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          commit_sha: ${{ env.COMMIT_SHA }}
          commit_branch: ${{ env.COMMIT_BRANCH }}
          allow_prod: ${{ env.ALLOW_PROD }}